### ISSUE TITLE
Visual Basic projects fail in version 1.1.1

### ISSUE THREAD

**Issue by amaijer** [sebastianlux/tfbuildtask-updateAssemblyInfo#2]
Version 1.1.1 adds an '@' in front of the version string, but that is invalid code in Visual Basic.

The resulting version lines look like this:
`
<Assembly: AssemblyVersion(@"1.0.0.0")>
<Assembly: AssemblyFileVersion(@"1.0.17066.3")>
`

Maybe you can add a check on file extension and only add the '@' for C# files?

**Comment by sebastianlux** [comment]
Hi amaijer,

thank you for reporting this issue!

I did follow your suggestion and now check the file extension and do not add the `@` in case of vb files.
Please try out the new [release](https://marketplace.visualstudio.com/items?itemName=sebastianlux.UpdateAssemblyInfo) to check if everything works as expected.

Sebastian

**Comment by amaijer** [comment]
Hi Sebastian,


Everything is working again. Thanks for fixing it so quickly.


André


________________________________
