### ISSUE TITLE
Extra character in AssemblyVersion

### ISSUE THREAD

**Issue by mccw** [sebastianlux/tfbuildtask-updateAssemblyInfo#3]
This is working well but I get an extra @ symbol in the AssemblyVersion.
![image](https://cloud.githubusercontent.com/assets/3137337/24772300/67c602f0-1ad6-11e7-82d4-e17f34bac614.png)

This is the code that produces the variable:
`function VersionNumber
{
	$versionRegex = "\d+\.\d+"
    $versionData = [regex]::matches($Env:BUILD_BUILDNUMBER,$versionRegex)

    # create the full version string
    $script:buildVer = "$Env:majorVersion.$Env:minorVersion.$versionData"
    Write-Host ("##vso[task.setvariable variable=octoVersion;]$buildVer")`

and this is the setup for the step;

![image](https://cloud.githubusercontent.com/assets/3137337/24772368/a5d72dda-1ad6-11e7-9a08-768f47140c5f.png)

and this is how the variable is displayed in the log:

![image](https://cloud.githubusercontent.com/assets/3137337/24772401/ca95a2dc-1ad6-11e7-9aba-fe3380143058.png)

So, based on the log, I'm not sure where the extra @ symbol is coming from.

**Comment by mccw** [comment]
I removed the @ symbols from the script and it appears to be working correctly now:
`                $attribute = $attributeName + '("' + $value + '")';
        }

        $fileContent = $fileContent -replace ($attributeName +'\({0,1}".*"\)'), $attribute`

**Comment by sebastianlux** [comment]
Hi mccw,

the extra `@` is intended. I added it in release *1.1.1*. This is to prevent the build from breaking when the content of an assembly attribute contains an escape character like `\`, e.g. *www.myurl\example*. 
This has no influence on the compiled assembly information of your application.

Hope that helps!

Sebastian
